# NumPy Functions

In [102]:
import numpy as np

## Argpartition()

In [103]:
# Random array
x = np.array([12, 10, 12, 0, 6, 8, 9, 1, 16, 4, 6, 0])

In [104]:
index_val = np.argpartition(x, -4)[-4:]
index_val

array([1, 8, 2, 0], dtype=int64)

In [105]:
np.sort(x[index_val])

array([10, 12, 12, 16])

## Allclose()

In [106]:
array1 = np.array([0.12,0.17,0.24,0.29])
array2 = np.array([0.13,0.19,0.26,0.31])

In [107]:
# with a tolerance of 0.1, it should return False:
np.allclose(array1,array2,0.1)

False

In [108]:
# with a tolerance of 0.2, it should return True:
np.allclose(array1,array2,0.2)

True

## Clip()

In [109]:
x = np.array([3, 17, 14, 23, 2, 2, 6, 8, 1, 2, 16, 0])

In [110]:
np.clip(x,2,5)

array([3, 5, 5, 5, 2, 2, 5, 5, 2, 2, 5, 2])

## Extract()

In [111]:
# Random integers
array = np.random.randint(20, size=12)
array

array([17, 14,  6, 10, 12,  4, 13,  4,  3, 11,  0, 10])

In [112]:
#  Divide by 2 and check if remainder is 1
cond = np.mod(array, 2)==1
cond

array([ True, False, False, False, False, False,  True, False,  True,
        True, False, False])

In [113]:
# Use extract to get the values
np.extract(cond, array)

array([17, 13,  3, 11])

In [114]:
# Apply condition on extract directly
np.extract(((array < 3) | (array > 15)), array)

array([17,  0])

## Where()

In [115]:
y = np.array([1,5,6,8,1,7,3,6,9])

In [116]:
# Where y is greater than 5, returns index position
np.where(y>5)

(array([2, 3, 5, 7, 8], dtype=int64),)

In [117]:
# First will replace the values that match the condition, second will replace the values that does not
np.where(y>5, "Hit", "Miss")

array(['Miss', 'Miss', 'Hit', 'Hit', 'Miss', 'Hit', 'Miss', 'Hit', 'Hit'],
      dtype='<U4')

## Percentile()

In [118]:
a = np.array([1,5,6,8,1,7,3,6,9])

In [119]:
print("50th Percentile of arr, axis = 0 : ",  
      np.percentile(a, 50, axis =0))

50th Percentile of arr, axis = 0 :  6.0


In [120]:
b = np.array([[10, 7, 4], [3, 2, 1]])

In [121]:
print("30th Percentile of arr, axis = 0 : ",  
      np.percentile(b, 30, axis =0))

30th Percentile of arr, axis = 0 :  [5.1 3.5 1.9]


# Pandas Functions

In [122]:
import pandas as pd

## read_csv(nrows=10)

In [128]:
import io
import requests

# I am using this online data set just to make things easier for you guys
url = "https://raw.github.com/vincentarelbundock/Rdatasets/master/csv/datasets/AirPassengers.csv"
s = requests.get(url).content

In [132]:
# read only first 10 rows
df = pd.read_csv(io.StringIO(s.decode('utf-8')),nrows=10 , index_col=0)
df

time  value
1   1949.000000    112
2   1949.083333    118
3   1949.166667    132
4   1949.250000    129
5   1949.333333    121
6   1949.416667    135
7   1949.500000    148
8   1949.583333    148
9   1949.666667    136
10  1949.750000    119

## map()

In [138]:
# create a dataframe
dframe = pd.DataFrame(np.random.randn(4, 3), columns=list('bde'), index=['India', 'USA', 'China', 'Russia'])
dframe

b         d         e
India   1.302245  0.571917  0.573815
USA    -0.481980 -0.464518  0.528452
China  -0.339589  1.244659 -0.518640
Russia  1.590290  1.839274 -0.250006

In [141]:
#compute a formatted string from each floating point value in frame
changefn = lambda x: '%.2f' % x

In [142]:
# Make changes element-wise
dframe['d'].map(changefn)

India      0.57
USA       -0.46
China      1.24
Russia     1.84
Name: d, dtype: object

## Apply()

In [143]:
# max minus mix lambda fn
fn = lambda x: x.max() - x.min()

In [144]:
# Apply this on dframe
dframe.apply(fn)

b    2.072270
d    2.303792
e    1.092456
dtype: float64

## isin()

In [158]:
# Using the dataframe we created for read_csv
filter1 = df["value"].isin([112]) 
filter2 = df["time"].isin([1949.000000]) 

In [159]:
df [filter1 & filter2]

time  value
1  1949.0    112

## copy()

In [160]:
# creating sample series 
data = pd.Series(['India', 'Pakistan', 'China', 'Mongolia']) 

In [173]:
# Assigning issue that we face
data1= data
# Change a value
data1[0]='USA'
# Also changes value in old dataframe
data

0         USA
1    Pakistan
2       China
3    Mongolia
dtype: object

In [161]:
# creating copy of series 
new = data.copy() 

In [162]:
# assigning new values 
new[1]='Changed value'

In [169]:
# printing data 
print(new) 
print(data) 

0            India
1    Changed value
2            China
3         Mongolia
dtype: object
0       India
1    Pakistan
2       China
3    Mongolia
dtype: object


## select_dtypes()

In [176]:
framex =  df.select_dtypes(include="float64")

In [177]:
framex

time
1   1949.000000
2   1949.083333
3   1949.166667
4   1949.250000
5   1949.333333
6   1949.416667
7   1949.500000
8   1949.583333
9   1949.666667
10  1949.750000

# Bonus:

## pivot_table()

In [182]:
# Create a sample dataframe
school = pd.DataFrame({'A': ['Jay', 'Usher', 'Nicky', 'Romero', 'Will'], 
      'B': ['Masters', 'Graduate', 'Graduate', 'Masters', 'Graduate'], 
      'C': [26, 22, 20, 23, 24]}) 

In [181]:
# Lets create a pivot table to segregate students based on age and course
table = pd.pivot_table(school, values ='A', index =['B', 'C'], 
                         columns =['B'], aggfunc = np.sum, fill_value="Not Available") 
  
table

B                 Graduate        Masters
B        C                               
Graduate 20          Nicky  Not Available
         22          Usher  Not Available
         24           Will  Not Available
Masters  23  Not Available         Romero
         26  Not Available            Jay

# Thank yoouuuuuuuu ! 